//menu data
export default [{
	name: "Disease",
	children: [{
		"name": "Others",
		"children": [{
			"name": "Benign_gynecologic_condition",
			"children": []
		}, {
			"name": "Black_leg_disease",
			"children": []
		}, {
			"name": "Canaliculitis",
			"children": []
		}, {
			"name": "Causing_nosocomial",
			"children": []
		}, {
			"name": "Cervicovaginal_microbiome_dysbiosis",
			"children": []
		}, {
			"name": "Chlamydia",
			"children": []
		}, {
			"name": "Chlamydiosis",
			"children": []
		}, {
			"name": "Cholera",
			"children": []
		}, {
			"name": "Clostridium_difficile_infection",
			"children": []
		}, {
			"name": "Clostridium_difficile_infection_",
			"children": []
		}, {
			"name": "Clostridium_difficile_infection(cdi)",
			"children": []
		}, {
			"name": "Cold_sores",
			"children": []
		}, {
			"name": "Colorectal_carcinoma",
			"children": [{
				"name": "Colon_cancer",
				"children": []
			}]
		}, {
			"name": "Complications_during_parturition",
			"children": []
		}, {
			"name": "Congenital_microcephaly",
			"children": []
		}, {
			"name": "Cryptosporidiosis",
			"children": []
		}, {
			"name": "Cutaneous_acanthamebiasis",
			"children": []
		}, {
			"name": "Cutaneous_burn",
			"children": []
		}, {
			"name": "Cutaneous_mycoses",
			"children": []
		}, {
			"name": "Dandruff",
			"children": []
		}, {
			"name": "Disease-free_",
			"children": []
		}, {
			"name": "Disseminated_trichosporonosis",
			"children": []
		}, {
			"name": "Diverticular_disease",
			"children": []
		}, {
			"name": "Dysfunction",
			"children": []
		}, {
			"name": "Dyspepsia",
			"children": []
		}, {
			"name": "Encephalopathy",
			"children": []
		}, {
			"name": "European_foulbrood",
			"children": []
		}, {
			"name": "Extraoral_abscesses",
			"children": []
		}, {
			"name": "Foul_odor",
			"children": []
		}, {
			"name": "Fungemia",
			"children": []
		}, {
			"name": "Furunculosis",
			"children": []
		}, {
			"name": "Gangrene",
			"children": []
		}, {
			"name": "Hemolytic_uremic_syndrome",
			"children": []
		}, {
			"name": "Heterophyiasis",
			"children": []
		}, {
			"name": "Hyalohyphomycosis",
			"children": []
		}, {
			"name": "Hydrocephalus",
			"children": []
		}, {
			"name": "Hyperthyroidism",
			"children": []
		}, {
			"name": "Interstitial_cystitis",
			"children": []
		}, {
			"name": "Lesions_in_humans",
			"children": []
		}, {
			"name": "Lungsaspergillosis",
			"children": []
		}, {
			"name": "Lyme_disease",
			"children": []
		}, {
			"name": "Lymphangitis",
			"children": []
		}, {
			"name": "Megaesophagus",
			"children": []
		}, {
			"name": "Metagonimiasis",
			"children": []
		}, {
			"name": "Muscle_aches",
			"children": []
		}, {
			"name": "Oligoasthenoteratozoospermia",
			"children": []
		}, {
			"name": "Oral_lichen_planus",
			"children": []
		}, {
			"name": "Oral_lichen_planus_",
			"children": []
		}, {
			"name": "Ostomyelitis",
			"children": []
		}, {
			"name": "Pathogenic",
			"children": []
		}, {
			"name": "Peritonitis",
			"children": []
		}, {
			"name": "Pig-bel_syndrome",
			"children": []
		}, {
			"name": "Pleuropulmonary_blastoma",
			"children": []
		}, {
			"name": "Polyomas",
			"children": []
		}, {
			"name": "Postmenopausal",
			"children": []
		}, {
			"name": "Primary_immunodeficiencies",
			"children": []
		}, {
			"name": "Probiotic",
			"children": []
		}, {
			"name": "Pulmonary_arterial_hypertension_associated_with_another_disease",
			"children": []
		}, {
			"name": "Red_water_disease",
			"children": []
		}, {
			"name": "Refractory_celiac_disease",
			"children": []
		}, {
			"name": "Rhinitis",
			"children": []
		}, {
			"name": "Roseola",
			"children": []
		}, {
			"name": "Scedosporiosis",
			"children": []
		}, {
			"name": "Seminal_hyperviscosity",
			"children": []
		}, {
			"name": "Splenic_disease",
			"children": []
		}, {
			"name": "Spondylodiscitis",
			"children": []
		}, {
			"name": "Suppuration_of_wounds",
			"children": []
		}, {
			"name": "Synovitis",
			"children": []
		}, {
			"name": "Synovitis_",
			"children": []
		}, {
			"name": "Systematic_fungemia",
			"children": []
		}, {
			"name": "Tumorous_abscesses",
			"children": []
		}, {
			"name": "Typhus",
			"children": []
		}, {
			"name": "Ulcers",
			"children": []
		}, {
			"name": "White-sutton_syndrome",
			"children": []
		}]
	}, {
		"name": "Cardiovascular_disease",
		"children": [{
			"name": "Atherosclerosis",
			"children": []
		}, {
			"name": "Coronary_heart_disease",
			"children": [{
				"name": "Coronary_artery_disease",
				"children": []
			}]
		}, {
			"name": "Endocarditis",
			"children": [{
				"name": "Bacterial_endocarditis",
				"children": []
			}]
		}, {
			"name": "Heart_failure",
			"children": []
		}, {
			"name": "Hypertension",
			"children": [{
				"name": "Preeclampsia",
				"children": []
			}]
		}]
	}, {
		"name": "Herpes_simplex_infection",
		"children": []
	}, {
		"name": "Liver_disease",
		"children": [{
			"name": "hepatitis,_alcoholic",
			"children": []
		}, {
			"name": "Non-alcoholic_fatty_liver_disease",
			"children": [{
				"name": "Non-alcoholic_steatohepatitis",
				"children": []
			}, {
				"name": "Non-alcoholic_steatohepatitis_",
				"children": []
			}]
		}]
	}, {
		"name": "Measles",
		"children": []
	}, {
		"name": "Respiratory_system_disease",
		"children": [{
			"name": "Atrophic_rhinitis",
			"children": []
		}, {
			"name": "Chronic_obstructive_pulmonary_disease",
			"children": [{
				"name": "Chronic_bronchitis",
				"children": []
			}]
		}, {
			"name": "Chronic_rhinosinusitis",
			"children": [{
				"name": "Chronic_rhinosinusitis_with_nasal_polyps",
				"children": []
			}]
		}, {
			"name": "Epiglottitis",
			"children": []
		}, {
			"name": "Idiopathic_pulmonary_fibrosis",
			"children": []
		}, {
			"name": "Lung_disease",
			"children": [{
				"name": "Acute_chest_syndrome",
				"children": []
			}]
		}, {
			"name": "Scarlet_fever",
			"children": []
		}, {
			"name": "Sinusitis",
			"children": [{
				"name": "Maxillary_sinusitis",
				"children": []
			}]
		}, {
			"name": "Whooping_cough",
			"children": []
		}]
	}, {
		"name": "Rubella",
		"children": []
	}, {
		"name": "Skin_disease",
		"children": [{
			"name": "Bullous_skin_disease",
			"children": [{
				"name": "Bullous_pemphigoid",
				"children": []
			}, {
				"name": "Cicatricial_pemphigoid",
				"children": []
			}, {
				"name": "Mucous_membrane_pemphigoid",
				"children": []
			}]
		}, {
			"name": "Buruli_ulcer",
			"children": []
		}, {
			"name": "Cellulitis",
			"children": [{
				"name": "Ludwigs_angina",
				"children": []
			}, {
				"name": "Ludwigs_angina_",
				"children": []
			}]
		}, {
			"name": "Eumycotic_mycetoma",
			"children": []
		}, {
			"name": "Granulomatous_dermatitis",
			"children": []
		}, {
			"name": "Inflammatory_skin_disease",
			"children": [{
				"name": "Acne",
				"children": []
			}, {
				"name": "Atopic_eczema",
				"children": [{
					"name": "Recalcitrant_atopic_dermatitis",
					"children": []
				}]
			}, {
				"name": "Psoriasis",
				"children": []
			}, {
				"name": "Psoriasis_",
				"children": []
			}]
		}, {
			"name": "Tinea_pedis",
			"children": []
		}, {
			"name": "Vitiligo",
			"children": []
		}]
	}, {
		"name": "Streptococcal_pharyngitis",
		"children": []
	}]
}]